# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
	# check these on https://fabricmc.net/versions.html
	minecraft_version=1.21.7
	loader_version=0.16.14
	loom_version=1.11-SNAPSHOT

# Mod Properties
	mod_version = 1.0.2
	maven_group = de.kxmischesdomi
	archives_base_name = just-end-anchor

# Dependencies
	fabric_version=0.128.1+1.21.7
