org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.8
loader_version=0.17.2
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version = 1.1
maven_group = de.kxmischesdomi
archives_base_name = just-end-anchor

# Dependencies
fabric_version=0.133.0+1.21.8
modmenu_version=15.0.0
